language: node_js

node_js:
  - "0.10"

after_success:
  - "npm install -g codeclimate-test-reporter"
  - "codeclimate < ./coverage/lcov.info"

notifications:
  email:
    on_success: change
    on_failure: always

env:
  global:
    - CODECLIMATE_REPO_TOKEN=8554890998589ec66cee39afbb33bcefe715174634b4bd2bcd1bbd4b5fdf2c93
